Movie_rental_store_Manager/Controllers/CustomerController.cs
using Microsoft.AspNetCore.Mvc;
using MovieRentalStoreManager.BLL.Entities;
using MovieRentalStoreManager.BLL.Interfaces;
using MovieRentalStoreManager.BLL.Services;

namespace MovieRentalStoreManager.App.Controllers
{
    public class CustomerController : AbstractController
    {
        public ICustomerService CustomerService { get; private set; }

        public CustomerController(ICustomerService customerService)
        {
            CustomerService = customerService;
        }

        public IActionResult Index()
        { 
            var result = CustomerService.List();

            return View(result.Value);
        }

        public IActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Customer customer)
        {
            var result = CustomerService.Add(customer);

            return RedirectToAction(nameof(Index));
        }

        public IActionResult Details(int id)
        {
            var result = CustomerService.FindById(id);

            return result.IsFailed ? RedirectToAction(nameof(Index)) : View(result.Value);
        }

        public IActionResult Edit(int id)
        {
            var result = CustomerService.FindById(id);

            return result.IsFailed ? RedirectToAction(nameof(Index)) : View(result.Value);
        }

        [HttpPost]
        public IActionResult Edit(int id, Customer customer)
        {
            var result = CustomerService.Update(id, customer);

            return result.IsSuccess ? RedirectToAction(nameof(Index)) : RedirectToAction(nameof(Index));
        }

        public IActionResult Delete(int id)
        {
            var result = CustomerService.Remove(id);

            return RedirectToAction(nameof(Index));
        }

        public IActionResult List()
        {
            var result = CustomerService.List();

            return result.IsSuccess ? View() : GetErrorResult(result.ToResult());
        }
    }
}

Movie_rental_store_Manager/Controllers/MovieController.cs
using Microsoft.AspNetCore.Mvc;
using MovieRentalStoreManager.BLL.Entities;
using MovieRentalStoreManager.BLL.Interfaces;

namespace MovieRentalStoreManager.App.Controllers
{
    public class MovieController : AbstractController
    {
        public IMovieService MovieService { get; private set; }

        public MovieController(IMovieService movieService)
        {
            MovieService = movieService;
        }

        public IActionResult Index()
        {
            var result = MovieService.List();

            return View(result.Value);
        }

        public IActionResult Add()
        {
            return View();
        }

        public IActionResult Details(int id)
        {
            var result = MovieService.FindById(id);

            return result.IsFailed ? RedirectToAction(nameof(Index)) : View(result.Value);
        }

        public IActionResult Edit(int id)
        {
            var result = MovieService.FindById(id);

            return result.IsFailed ? RedirectToAction(nameof(Index)) : View(result.Value);
        }

        [HttpPost]
        public IActionResult Create(Movie movie)
        {
            var result = MovieService.Add(movie);

            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        public IActionResult Edit(int id, Movie movie)
        {
            var result = MovieService.Update(id, movie);

            return result.IsSuccess ? RedirectToAction(nameof(Index)) : RedirectToAction(nameof(Index));
        }

        public IActionResult Delete(int id)
        {
            var result = MovieService.Remove(id);

            return RedirectToAction(nameof(Index));
        }

        public IActionResult List()
        {
            var result = MovieService.List();

            return result.IsSuccess ? View() : GetErrorResult(result.ToResult());
        }
    }
}

Movie_rental_store_Manager/Controllers/RentalController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using MovieRentalStoreManager.BLL.Entities;
using MovieRentalStoreManager.BLL.Interfaces;

namespace MovieRentalStoreManager.App.Controllers
{
    public class RentalController : AbstractController
    {
        public IRentalService RentalService { get; private set; }

        public RentalController(IRentalService rentalService)
        {
            RentalService = rentalService;
        }

        public IActionResult Index()
        {
            var result = RentalService.List();

            return View(result.Value);
        }

        public IActionResult Add()
        {
            ViewBag.MovieId = new SelectList(RentalService.ListMovies().Value,"Id", "Name");
            ViewBag.CustomerId = new SelectList(RentalService.ListCustomers().Value,"Id", "Name");

            return View();
        }

        public IActionResult Details(int id)
        {
            var result = RentalService.FindById(id);

            return result.IsFailed ? RedirectToAction(nameof(Index)) : View(result.Value);
        }

        public IActionResult Edit(int id)
        {
            var result = RentalService.FindById(id);

            ViewBag.MovieId = new SelectList(RentalService.ListMovies().Value, "Id", "Name",result.Value.MovieId);
            ViewBag.CustomerId = new SelectList(RentalService.ListCustomers().Value, "Id", "Name", result.Value.CustomerId);

            return result.IsFailed ? RedirectToAction(nameof(Index)) : View(result.Value);
        }

        [HttpPost]
        public IActionResult Create(Rental rental)
        {
            var result = RentalService.Add(rental);

            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        public IActionResult Edit(int id, Rental rental)
        {
            var result = RentalService.Update(id, rental);

            return result.IsSuccess ? RedirectToAction(nameof(Index)) : RedirectToAction(nameof(Index));
        }

        public IActionResult Delete(int id)
        {
            var result = RentalService.Remove(id);

            return RedirectToAction(nameof(Index));
        }

        public IActionResult List()
        {
            var result = RentalService.List();

            return result.IsSuccess ? View() : GetErrorResult(result.ToResult());
        }
    }
}

Movie_rental_store_Manager/Controllers/UserController.cs
using FluentResults;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using MovieRentalStoreManager.BLL.Entities;
using MovieRentalStoreManager.BLL.Interfaces;
using NuGet.Protocol.Plugins;

namespace MovieRentalStoreManager.App.Controllers
{
    public class UserController : AbstractController
    {
        public IUserService UserService { get; private set; }

        public UserController(IUserService userService)
        {
            UserService = userService;
        }

        public IActionResult Index()
        {
            var result = UserService.List();

            return View(result.Value);
        }

        public IActionResult Add()
        {
            return View();
        }

        public IActionResult Details(int id)
        {
            var result = UserService.FindById(id);

            return result.IsFailed ? RedirectToAction(nameof(Index)) : View(result.Value);
        }

        public IActionResult Edit(int id)
        {
            var result = UserService.FindById(id);

            return result.IsFailed ? RedirectToAction(nameof(Index)) : View(result.Value);
        }

        [HttpPost]
        public IActionResult Create(User user)
        {
            var result = UserService.Add(user);

            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        public IActionResult Edit(int id, User user)
        {
            var result = UserService.Update(id, user);

            return result.IsSuccess ? RedirectToAction(nameof(Index)) : RedirectToAction(nameof(Index));
        }

        public IActionResult Delete(int id)
        {
            var result = UserService.Remove(id);

            return RedirectToAction(nameof(Index));
        }

        public IActionResult List()
        {
            var result = UserService.List();

            return result.IsSuccess ? View() : GetErrorResult(result.ToResult());
        }
    }
}

Movie_rental_store_Manager/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Movie_rental_store_Manager</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Movie_rental_store_Manager.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Movie_rental_store_Manager</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Index">Usuario</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Customer" asp-action="Index">Cliente</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Movie" asp-action="Index">Filme</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Rental" asp-action="Index">Locação</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Gabriel Bernardo Bezerra de Souza
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>